Bug/96 log object
Atlas-Assistance-Dogs/atlas-dogs pull request #115
Opened 2021-07-24 21:29 UTC by deb761

# Changes

Added references to log object
Removed ContactLog object
Updated Contact layout

# Issues Closed
#96

2021-07-31 05:36 UTC, atlasjen requested changes
I am trying to push this branch to a clean dev scratch org and am getting this error:
───────────────────────────────────────────────────────────────────────
2021-07-30 22:35:17: Error  N/A           Your attempt to delete AtlasEmailTemplates cannot be completed because it contains the following email templates.: GeneralInfoServiceDog, TeamFacilitatorArea, TeamSetinMotionResponse, TrainerLocation
2021-07-30 22:35:20: Return code: 1
stderr: ERROR running force:source:push:  Push failed.


Return code: 1
stderr: ERROR running force:source:push:  Push failed.

2021-08-01 04:54 UTC, deb761 commented
Problems resolved.  I just pushed this branch to a fresh scratch org, and it deployed along with the sample data.

2021-08-05 00:39 UTC, atlasjen approved these changes

2021-08-05 00:40 UTC, atlasjen commented
please change the log name to be autonumbered.

2021-08-05 00:40 UTC, merged