Added a new field
Atlas-Assistance-Dogs/atlas-dogs pull request #499
Opened 2023-10-20 16:45 UTC by mguillendev

# Critical Changes

# Changes

- Created the "Training Start Date" custom field on Team object and located in the correct position in the team layout. 
- Added the permission set to view and edit the field for Altas Super Users and Atlas Teams.

# Issues Closed

#497

2023-10-21 17:23 UTC, deb761 requested changes
Looks good except for the accidentally-deleted permission.

2023-10-21 17:23 UTC, deb761 commented on force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
> -    <fieldPermissions>
Ooops!  We need to leave this permission here.

2023-10-22 19:57 UTC, deb761 approved these changes

2023-10-22 19:57 UTC, deb761 commented on force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
> -    <fieldPermissions>
My bad.  You're removing a duplicate.

2023-10-23 00:57 UTC, atlasjen commented
looks good.

2023-10-23 00:57 UTC, merged