Added the checkbox Text Messages Approved
Atlas-Assistance-Dogs/atlas-dogs pull request #500
Opened 2023-10-20 17:21 UTC by mguillendev

# Critical Changes

# Changes

- Added the checkbox Text Messages Approved to Contacts object. 
- Located in the Atlas Contact Layout.
- Added the permission set to view/edit the Text Messages Approved field for Atlas Super Users and Atlas Base

# Issues Closed

#498

2023-10-21 17:24 UTC, deb761 requested changes
Looks good except for the missing permission.

2023-10-21 17:24 UTC, deb761 commented on force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
> -    <fieldPermissions>
This needs to be added back here, also.

2023-10-22 19:56 UTC, deb761 commented on force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
> -    <fieldPermissions>
My bad.  You're removing a duplicate.

2023-10-22 19:56 UTC, deb761 approved these changes

2023-10-23 01:04 UTC, atlasjen commented
I see this in the page layout editor
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/130f802c-6358-4085-950d-d23ac7d4961b)

But I do not see it in the page layout itself
![image](https://github.com/Atlas-Assistance-Dogs/atlas-dogs/assets/66139437/8535da43-23aa-4a21-8ca6-0aad505ad9f0)

I'm guessing some permission setting ?

2023-10-24 02:23 UTC, atlasjen requested changes
see earlier comment on changes needed.

2023-10-24 07:27 UTC, mguillendev commented on force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
> -    <fieldPermissions>
Sorry, I don't understand. Do I need to add something?

2023-10-25 00:22 UTC, deb761 commented
Did you try a hard page refresh?  I see the new field in AtlasSuperUser and the AtlasBase permission sets.

2023-10-25 00:23 UTC, deb761 commented on force-app/main/default/permissionsets/AtlasSuperUser.permissionset-meta.xml
> -    <fieldPermissions>
No, when you pulled the code down, it removed an extra field permission.  On first review, I thought you had accidentally removed the permission altogether.

2023-10-25 19:08 UTC, atlasjen commented
ok. with a full org redeploy it's there. thanks!

2023-10-25 19:08 UTC, merged